### ISSUE TITLE
callbackOnInview -  Event listener when Item is in view not just animated

### ISSUE THREAD

**Issue by functionandform** [jshjohnson/Animate#11]
I would like to run a function when element is in view port but the callbackOnAnimate only works if an animation has taken place. This would prevent me having to have further scroll events.

**Comment by jshjohnson** [comment]
Hey @toddpadwick,

This would be a super simple PR - I would be happy to review it? 👍

**Comment by toddpadwick** [comment]
HI @jshjohnson thanks for your response... and merry christmas!
I am not really a JS developer (just HTML/CSS and basic jquery) so unfortunately doing this update myself is a little beyond my expertise :(
