### ISSUE TITLE
Animate Timing.

### ISSUE THREAD

**Issue by feroz39** [jshjohnson/Animate#16]
Is there a way to set the animate time?

**Comment by jshjohnson** [comment]
If you mean the duration of the animation, yes there is. You would set it in your CSS :)

**Comment by feroz39** [comment]
Thanks for replay. I wonder if there is a way to set time to delay. Please let me know if there is any easy way.

**Comment by jshjohnson** [comment]
See here: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-duration

And https://developer.mozilla.org/en-US/docs/Web/CSS/animation-delay
