### ISSUE TITLE
Optional parameter to test horizontal position of element on screen (as well as vertical).

### ISSUE THREAD

**Issue by jshjohnson** [jshjohnson/Animate#4]
For example: 

````js
    var animate = new Animate({
        offset: [0.5, 0.25],
    });
````

This would test to see whether at least 50% of the elements height was within the viewport as well as 25% of the elements width. Useful for horizontal scrolling pages.

**Comment by camslice** [comment]
👍

**Comment by jshjohnson** [comment]
This is now possible as of version 1.3.1. See: https://github.com/jshjohnson/Animate#offset
