### ISSUE TITLE
Error: "Cannot read property '_debounce' of undefined" on line 32 of animate.js when using require.js

### ISSUE THREAD

**Issue by camslice** [jshjohnson/Animate#6]
animate.js would appear to be AMD compliant based on the code at the start of the file, however it doesn't seem to play nice with require.js

i've tried adding a shim to export "Animate" but that doesn't work

any clues?

**Comment by jshjohnson** [comment]
Hi @camslice,

Did you install Animate via NPM?

Thanks

**Comment by camslice** [comment]
ah no I didn't

does that install dependencies?

what are the dependencies?

**Comment by jshjohnson** [comment]
Hmm, it should have dependencies bundled with it - I'll investigate this for you. Using NPM should get round this for you in the meantime.

Thanks

**Comment by jshjohnson** [comment]
Ah on second thoughts, _debounce isn't actually from a dependency, it's one of Animate's own methods.

Could you send over the code that initialises Animate please? A full error would also be helpful. Thanks!

**Comment by camslice** [comment]
Will do. I'll have to dig it out of a larger project so you're not sifting
through junk. Hopefully get to it tonight. Thanks Josh

**Comment by camslice** [comment]
Hi Josh, I've stripped back the code to the bare minimum. Both animate.js and animate.min.js throw errors. This require.js configuration is based on this multipage config: https://github.com/requirejs/example-multipage
[Archive.zip](https://github.com/jshjohnson/Animate/files/410985/Archive.zip)

Thanks again, Cam

**Comment by jshjohnson** [comment]
Hi @camslice,

Thanks for the reduced test case! I have pushed an update that should resolve this issue for you (version 1.2.6).

if you have any further issues, let me know.

Thanks
