### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by camslice** [jshjohnson/Animate#7]
Hi Josh,

Thanks for the require.js UMD wrapper fix. We're not out of the woods yet though. I've updated the test case: 
[Archive.zip](https://github.com/jshjohnson/Animate/files/411084/Archive.zip)

Cheers, Cam

**Comment by camslice** [comment]
To clarify, I've also tried putting the Animate call inside domReady, just to make sure the root of the document actually exists at the time it is called. Alas, the error remains.

**Comment by jshjohnson** [comment]
Hmmm, let me investigate this. I think this is still the UMD wrapper causing issues.

**Comment by jshjohnson** [comment]
Hi @camslice,

I have pushed an update (version 1.2.7) that should resolve this issue. I've tested it with RequireJS (using your test case files) and Browserify. 

Thanks,
Josh
